[WIP] Add bluetooth support
AsteroidOS/meta-sparrow-hybris pull request #1
Opened 2017-02-16 18:01 UTC by daniellandau

This is work in progress. So far I have added a kernel patch from meta-dory-hybris, and verified that it compiles.

2017-03-13 18:17 UTC, daniellandau commented
These changes work on a wren. I don't have a sparrow to test on.

2017-03-13 21:43 UTC, Lrs121 commented
I'll check function this weekend, but at a glance it looks good to me.

2017-03-17 02:03 UTC, Lrs121 requested changes
Direct merge breaks build.
I have concerns in weaking the security of the device by reverting a security patch.
SRCREV is invalid in the selected tree, this is the key offender in breaking the build.

If it's an issue on my end please let me know and I'll adapt to fix it.

2017-03-17 02:03 UTC, Lrs121 commented on recipes-kernel/linux/linux-sparrow_mm-mr1.bb
> +    file://0001-Revert-Sparrow-audio-security-patch-for-CVE-2016-206.patch \
Why are we reverting a security patch?

2017-03-17 02:03 UTC, Lrs121 commented on recipes-kernel/linux/linux-sparrow_mm-mr1.bb
> +SRCREV = "00f21f748f01888888909f9f58280f5a363cd5f9"
Invalid srcrev - breaks build
`ERROR: linux-sparrow-3.10+marshmallow-r0 do_fetch: Fetcher failure: Unable to find revision 00f21f748f01888888909f9f58280f5a363cd5f9 in branch android-msm-sparrow-3.10-marshmallow-mr1-wear-release even from upstream`

2017-03-17 02:03 UTC, Lrs121 commented on recipes-kernel/linux/linux-sparrow_mm-mr1.bb
> +SRCREV = "00f21f748f01888888909f9f58280f5a363cd5f9"
[log.do_fetch.1499.txt](https://github.com/AsteroidOS/meta-sparrow-hybris/files/849453/log.do_fetch.1499.txt)

2017-03-17 06:13 UTC, daniellandau commented on recipes-kernel/linux/linux-sparrow_mm-mr1.bb
> +SRCREV = "00f21f748f01888888909f9f58280f5a363cd5f9"
So it seems. For some reason the [wren tree](https://android.googlesource.com/kernel/msm/+log/android-msm-wren-3.10-marshmallow-mr1-wear-release) has commits specifically mentioning sparrow that are not in the [sparrow tree](https://android.googlesource.com/kernel/msm/+log/android-msm-sparrow-3.10-marshmallow-mr1-wear-release). I wonder what's up with that. Maybe you could try with the wren branch even for sparrow?

2017-03-17 06:15 UTC, daniellandau commented on recipes-kernel/linux/linux-sparrow_mm-mr1.bb
> +    file://0001-Revert-Sparrow-audio-security-patch-for-CVE-2016-206.patch \
The kernel failed to compile for me with that patch and since the wren doesn't even have a speaker I didn't think much of it. You might want to figure out a better way to fix the linking issues, or perhaps with a sparrow defconfig there are no issues.

2017-07-05 23:40 UTC, hadenodom commented
What's up with this?  Is @Lrs121 still active?  Anyone with write access that can move this forward?

2017-07-06 00:26 UTC, Lrs121 commented
I'm kinda life supporting sparrow at the moment. Since I graduated a lot of my time is currently spent on trying to find a job and after that I have a large backlog of things to work on; this included.

This patch needs an in depth rewrite, or to be rewritten from scratch, to get bluetooth working on sparrow. There are a lot of wren specific change that were added to this pull that do not apply to sparrow and its kernel. There are some changes that might be usable if done by hand. I personally favor closing this pull request but I have left it open for now to make it known that bluetooth still is not working.

I remember attempting get it working using this pull as a template but I did not get it working. I lost the changes I made when I accidentally destroyed my projects drive. I think it needed some kernel config changes, which is beyond my scope of knowledge.

2017-07-08 02:27 UTC, hadenodom commented
I wish I knew enough about how linux handles bluetooth to be able to help.  I'll take a stab at this, but I doubt I'll be able to make it work with my limited knowledge.  I'll ask on the IRC and see if anyone has a sparrow device and is more knowledgable and able to help.

2017-07-08 03:25 UTC, Lrs121 commented
The documentation on the AsteroidOS website is a great place to get a basic understanding. If you get a framework started, go a head and open a WIP pull request and I'll help out where I can.

2019-01-26 22:47 UTC, FlorentRevest commented
Implemented by https://github.com/AsteroidOS/meta-sparrow-hybris/commit/472f7fa634cf481bafa21fa5ebdca7ad6e83facb & https://github.com/AsteroidOS/meta-sparrow-hybris/commit/4b6e5cb2463c9eb6c29691fbaffeaae0fa5f19bb

2019-01-26 22:47 UTC, closed without merging